

export const products = [
    {
        id : 1,
        name : 'Google Pixle 3XL',
        discreption : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto praesentium exercitationem eius sint eum. Ipsam consequuntur vitae, minus doloribus maiores excepturi sed nihil ducimus! Inventore fuga tempora temporibus magnam laboriosam.',
        img : 'img/download (3).jpeg',
        inCart : false,
        price : 900,
        company : 'Google',
        count : 0,
    },
    {
        id : 2,
        name : 'Samsung Galaxy S10',
        discreption : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto praesentium exercitationem eius sint eum. Ipsam consequuntur vitae, minus doloribus maiores excepturi sed nihil ducimus! Inventore fuga tempora temporibus magnam laboriosam.',
        img : 'img/download (1).jpeg',
        inCart : false,
        price : 1000,
        company : 'Google',
        count : 0,
    },
    {
        id : 3,
        name : 'Iphone 10s max',
        discreption : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto praesentium exercitationem eius sint eum. Ipsam consequuntur vitae, minus doloribus maiores excepturi sed nihil ducimus! Inventore fuga tempora temporibus magnam laboriosam.',
        img : 'img/download.jpeg',
        inCart : false,
        price : 1100,
        company : 'Google',
        count : 0,
    },
    {
        id : 4,
        name : 'Huawie P30 Pro',
        discreption : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto praesentium exercitationem eius sint eum. Ipsam consequuntur vitae, minus doloribus maiores excepturi sed nihil ducimus! Inventore fuga tempora temporibus magnam laboriosam.',
        img : 'img/download (2).jpeg',
        inCart : false,
        price : 1000,
        company : 'Google',
        count : 0,
    },
    {
        id : 5,
        name : 'Samsung Tablet',
        discreption : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto praesentium exercitationem eius sint eum. Ipsam consequuntur vitae, minus doloribus maiores excepturi sed nihil ducimus! Inventore fuga tempora temporibus magnam laboriosam.',
        img : 'img/download (4).jpeg',
        inCart : false,
        price : 1200,
        company : 'Google',
        count : 0,
    },
    {
        id : 6,
        name : 'Razer Blade 2019',
        discreption : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto praesentium exercitationem eius sint eum. Ipsam consequuntur vitae, minus doloribus maiores excepturi sed nihil ducimus! Inventore fuga tempora temporibus magnam laboriosam.',
        img : 'img/download (5).jpeg',
        inCart : false,
        price : 2100,
        company : 'Google',
        count : 0,
    },
    {
        id : 7,
        name : 'Mac Book Pro',
        discreption : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto praesentium exercitationem eius sint eum. Ipsam consequuntur vitae, minus doloribus maiores excepturi sed nihil ducimus! Inventore fuga tempora temporibus magnam laboriosam.',
        img : 'img/mbp15touch-space-select-201807.jpeg',
        inCart : false,
        price : 2500,
        company : 'Google',
        count : 0,
    },
    {
        id : 8,
        name : 'Dell XPS 15',
        discreption : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto praesentium exercitationem eius sint eum. Ipsam consequuntur vitae, minus doloribus maiores excepturi sed nihil ducimus! Inventore fuga tempora temporibus magnam laboriosam.',
        img : 'img/download (6).jpeg',
        inCart : false,
        price : 2100,
        company : 'Google',
        count : 0,
    },
]